version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  lint:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn lint

workflows:
    lint-and-test:
      jobs:
        - lint
        - node/test:
            pkg-manager: yarn
