version: 2.1

orbs:
  node: circleci/node@1.1.6

defaults: &defaults
  working_directory: ~/keycap
  executor:
    name: node/default

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run:
          name: "Build packages"
          command: yarn build
      - persist_to_workspace:
          root: ~/keycap
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/keycap
      - run:
          name: "JavaScript Linter"
          command: yarn lint --quiet --format junit -o reports/js-lint-results.xml
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports
            JEST_JUNIT_OUTPUT_NAME: js-test-results.xml
          command: yarn test -i --ci --coverage --reporters="default" --reporters="jest-junit"
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - run:
          name: "Uploading coverage"
          command: yarn codecov
      - persist_to_workspace:
          root: ~/keycap
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/keycap
      - run:
          name: Publish package
          command: yarn lerna publish

workflows:
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
